# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Quick_search
                                 A QGIS plugin
 Quick_search
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-20
        copyright            : (C) 2023 by Sakal Mykhailo
        email                : 53861tmmb@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Quick_search class from file Quick_search.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Quick_search import Quick_search
    return Quick_search(iface)
